version: "3"
services:
  deno-app:
    build: .
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DENO_ENV=development
    command: ["deno", "run", "--watch", "-A", "main.ts"]
